name: SkyWelcome
version: '1.1.0-DEV-3'
main: com.github.lukesky19.skywelcome.SkyWelcome
api-version: '1.21'
load: STARTUP
author: lukeskywlker19
softdepend:
    - HeadDatabase

commands:
    skywelcome:
        description: The base command.
permissions:
    skywelcome.command.reload:
        description: Permission to reload the plugin.
        default: op
    skywelcome.command.help:
        description: Permission to view the plugin's help message.
        default: op
    skywelcome.command.toggle.join:
        description: Toggle the individual player's join message.
        default: op
    skywelcome.command.toggle.leave:
        description: Toggle the individual player's leave message.
        default: op
    skywelcome.command.toggle.quit:
        description: Toggle the individual player's quit message.s
        default: op
    skywelcome.command.toggle.motd:
        description: Toggle the individual player's motd message.
        default: op
    skywelcome.command.gui.join:
        description: Permission to open the join message selection GUI.
        default: op
    skywelcome.command.gui.quit:
        description: Permission to open the quit message selection GUI.
        default: op
    skywelcome.command.gui.leave:
        description: Permission to open the leave message selection GUI.
        default: op