config-version: 1.5.0.0
# The name of the locale file to use in skywelcome/locale, minus the file extension (.yml)
locale: en_US
# Should join messages be enabled globally?
global-join-toggle: true
# Should quit/leave messages be enabled globally?
global-quit-toggle: true
# Should the MOTD messages be enabled?
global-motd-toggle: true
# Join messages
# The first message will be used by default.
join-messages:
    -   permission: "skywelcome.join.default"
        message: "<gray>[<gray><green>+</green><gray>]</gray> <papi:essentials_nickname>"
motd:
    - "Welcome to the server, <papi:essentials_nickname>!"
# Leave/Quit messages
# The first message will be used by default.
quit:
    -   permission: "skywelcome.leave.default"
        message: "<gray>[<gray><red>-</red><gray>]</gray> <papi:essentials_nickname>"
welcome-rewards:
    enabled: true
    # Should players who welcome a new player who has logged out be rewarded?
    reward-offline-joins: false
    cash: 50
    item:
        item-type: DIAMOND
        amount: 1
    commands:
        - "give %player_name% emerald 1"
    messages:
        - "<aqua>Thanks for welcoming a new player. Enjoy this reward: <green>$50</green></aqua>"