config-version: 1.1.0-DEV-1
options:
    # Should join messages be enabled globally?
    joins: true
    # Should quit/leave messages be enabled globally?
    quits: true
    # Should the MOTD message be enabled?
    motd: true
join:
    # The first message will be used by default.
    0:
        permission: "skywelcome.join.default"
        message: "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> %player_name%'><gray>[<gray><green>+</green><gray>]</gray> %essentials_nickname%</hover>"
motd:
    contents:
        - "Welcome to the server, %essentials_nickname%!"
quit:
    # The first message will be used by default.
    0:
        permission: "skywelcome.leave.default"
        message: "<hover:show_text:'<yellow>Username</yellow><gray>:</gray> %player_name%'><gray>[<gray><red>-</red><gray>]</gray> %essentials_nickname%</hover>"